spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/ghes-3.1/ghes-3.1.yaml
namespace: ApiClients\Client\GitHubEnterprise
destination:
  root: ../
  source: clients
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
subSplit:
  templatesDir: ../templates
  branch: v0.2.3.1.x
  subSplitConfiguration: etc/config.subsplit-publish.json
  fullName: GitHub Enterprise (v3.1) {{ section }}
  vendor: api-clients
  sectionGenerator:
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\OperationIdSlash
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\WebHooks
  rootPackage:
    name: github-enterprise
    repository: git@github.com:php-api-clients/github.git
  sectionPackage:
    name: github-enterprise-{{ section }}
    repository: git@github.com:php-api-clients/github-{{ section }}.git
