on:
  push:
    branches:
      - v0.2.3.6.x

jobs:
  publis_sub_splits:
    runs-on: ubuntu-latest
    name: Publish Sub-split
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
      - uses: "ramsey/composer-install@v2"
      - run: php utils/repos.php
        name: Create repositories
        env:
          SUBSPLIT_GITHUB_TOKEN: ${{ secrets.SUBSPLIT_GITHUB_TOKEN }}
      - uses: frankdejonge/use-github-token@1.0.1
        with:
          authentication: 'wyrihaximus:${{ secrets.SUBSPLIT_GITHUB_TOKEN }}'
          user_name: 'Cees-Jan Kiewiet'
          user_email: 'ceesjank@gmail.com'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v2
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh-d-101'
      - uses: frankdejonge/use-subsplit-publish@main
        env:
          GITHUB_TOKEN: ${{ secrets.SUBSPLIT_GITHUB_TOKEN }}
        with:
          source-branch: 'v0.2.3.6.x'
          config-path: './etc/config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
